### ISSUE TITLE
表情不显示

### ISSUE THREAD

**Issue by fooller** [jkchao/vue-emoji#5]
https://dn-mhke0kuv.qbox.me/ 
是不是因为这个地址无法访问的原因呢？

**Comment by fooller** [comment]
我改了你 两段代码就可以用了 楼主请看：
第一：
在main.js里边，我把
Vue.prototype.emoji = emoji
改成
Vue.prototype.$emoji = emoji
第二：
在/src/compents/emoji.vue里边，我把
  <span 
              class="emoji-item"
              :title="emoji"
              :class="'sprite-' + getPureName(emoji)"></span>
改成
<span 
              class="emoji-item"
              v-html="$emoji(emoji)"
              :class="'sprite-' + getPureName(emoji)"></span>
第三：
在app.js里边，我把
<transition-group tag="div" name="list" class="comment">
      <p v-for="(item) in data" :key="item" class="item">
        <span v-html="emoji(item)"></span>
      </p>
    </transition-group>
改成了
<transition-group tag="div" name="list" class="comment">
      <p v-for="(item) in data" :key="item" class="item">
        <span v-html="$emoji(item)"></span>
      </p>
  </transition-group>

年前我用过楼主的代码，是好用的，年后就不可以了，并且看楼主近一年都没修改过代码，也许Vue版本的问题吧！

另外：感谢楼主精致的代码！看完学到了很多，也很享受！
     

                   祝好：fooller

**Comment by jkchao** [comment]
@fooller 大图片挂了 - -

**Comment by jkchao** [comment]
@fooller 现在应该可以了

**Comment by fooller** [comment]
我的项目里已经用了你这套代码。这个大图片挂了不要紧，github上所有的项目，带表情的都不显示了，我改了代码就可以用了呢，就算大表情挂了也能显示

**Comment by jkchao** [comment]
来个 PR 挺不错的😄
