### ISSUE TITLE
ios打开表情时，读不出来，然后Vue自动刷新

### ISSUE THREAD

**Issue by SamHz** [jkchao/vue-emoji#9]
大兄弟，ios打开表情时，读不出来，然后页面自动刷新，这个怎么办？

**Comment by jkchao** [comment]
@SamHz 页面自动刷新，好像和这个插件并没有什么关系。

**Comment by SamHz** [comment]
@jkchao 我昨天已经找到原因了，因为你这个表情包，太大了，IOS对浏览器分配的存储有限制的，缓存不过来后就会读不出来显示QuotaExceededError出错字样，当我把大量的表情从数组中移出后就可以读取了，或者改用浏览器无痕模式也可以，android也加载很吃力，所以有必要改成异步加载表情

**Comment by jkchao** [comment]
@SamHz 我觉得手机端可以定制一些 emoji 表情（原理和这个一样），这样就不用加载这么多了，我上家公司就是这么做的 😂
